version: '3'

services:
  ma_super_app:
    image: ma_super_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: my_user
      DB_PASSWORD: my_password
      DB_NAME: my_database

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_DATABASE: my_database
